version: "3"
services:
    php-fpm:
        build: install/php-fpm
        ports:
            - 9010:9000
        volumes:
            - ./code:/var/www/html/
        links:
            - db

    nginx:
        build: install/nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html/
        links:
            - php-fpm

    db:
        image: mysql:8.0
        container_name: db80
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: MyDB
            MYSQL_USER: MyDB
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Jakarta
        volumes:
            - /docker/db/data:/var/lib/mysql
            - /docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

